// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD87OHMerO35Xu0Hm1Q94G9KK-8vKSjeVw',
    appId: '1:736376001167:web:7f3cf153d3041127be96fa',
    messagingSenderId: '736376001167',
    projectId: 'medico-c84bc',
    authDomain: 'medico-c84bc.firebaseapp.com',
    storageBucket: 'medico-c84bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBEIqbc5TV5MQN_Rh-DBVNNVHxU3CiCZ4',
    appId: '1:736376001167:android:d4c6e4225d7b39b4be96fa',
    messagingSenderId: '736376001167',
    projectId: 'medico-c84bc',
    storageBucket: 'medico-c84bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaT-3RaC2kKMSLJtsiA0HWATRDWcnlbqg',
    appId: '1:736376001167:ios:5e6bec875fbf0986be96fa',
    messagingSenderId: '736376001167',
    projectId: 'medico-c84bc',
    storageBucket: 'medico-c84bc.firebasestorage.app',
    iosBundleId: 'com.example.medico',
  );
}
